### PR TITLE
Reversed an 'author' tuple, issue #10

### PR DESCRIPTION
**Pull request by MaciejKarasek**
Related to issue #10

### CODE REVIEW

**Review by bennett-diaz — COMMENTED** [review]
Hey Maciej. Thank you for your contribution. Did you test this?

You can see that your change has logic errors. To provide an example: whereas before the author was stored as `Stone, Brad`, your change transforms it to `darB ,enotS`. The desired output is actually `Brad Stone`, so the comma will need to be removed in addition to flipping first and last name properly.

**Comment by MaciejKarasek** [comment]
Ah righ, my bad, so `author` variable is stored just as string `"Lastname, Firstname"` not like tuple `("Lastname", "Firstname")`. Sorry, I'm gonna correct this.

**Review by bennett-diaz — APPROVED** [review]

**Comment by bennett-diaz** [comment]
Good work @MaciejKarasek. More broadly I recommend installing a linter and/or code formatter (if you don't already have) since some in-line comments were not aligned to PEP8. Anyway thank you for the contribution.

**Comment by MaciejKarasek** [comment]
Thanks for the advice, I'll check it out!

**Pull request merged**
